### ISSUE TITLE
add to awesome-yazi

### ISSUE THREAD

**Issue by AnirudhG07** [boydaihungst/restore.yazi#1]
Hi, cool plugin!
Would you like to add it to [awesome-yazi](https://github.com/AnirudhG07/awesome-yazi)? It would be amazing addition to the list!

Thank you

**Comment by boydaihungst** [comment]
Absolutely! Feel free to at it to the list. 👍

**Comment by AnirudhG07** [comment]
It would be nice if you made the PR for all your plugins made. Thanks
