### ISSUE TITLE
GitHub account required for install

### ISSUE THREAD

**Issue by hezy** [boydaihungst/restore.yazi#2]
When trying to install the restore.yazi plugin by using ` ya pack -a boydaihungst/restore.yazi`, I am asked for GitHub username and password. I guess this is a matter of the definitions for this repository. People should not be required to have a GitHub account to install and use software that has no real relation to GitHub.

**Comment by boydaihungst** [comment]
Try this:
`ya pack -a boydaihungst/restore`. I forgot to remove .yazi

**Comment by boydaihungst** [comment]
D
